/* eslint-disable */
/**
 * Stub generated by BotSwan scaffold.
 * Run `npx convex dev` to regenerate from your deployment.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
