/* eslint-disable */
/**
 * Stub generated by BotSwan scaffold.
 * Run `npx convex dev` to regenerate from your deployment.
 */
import type { AnyApi, AnyComponents } from "convex/server";
import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema.js";

export declare const api: AnyApi;
export declare const internal: AnyApi;
export declare const components: AnyComponents;

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
