/* eslint-disable */
/**
 * Stub generated by BotSwan scaffold.
 * Run `npx convex dev` to regenerate from your deployment.
 */
import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export type TableNames = keyof DataModel["tables"];

export type Doc<TableName extends TableNames> = DataModel["tables"][TableName]["document"];

export type Id<TableName extends TableNames> = DataModel["tables"][TableName]["id"];
