/* eslint-disable */
/**
 * Stub generated by BotSwan scaffold.
 * Run `npx convex dev` to regenerate from your deployment.
 */
import {
  actionGeneric,
  httpActionGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
  mutationGeneric,
  queryGeneric,
} from "convex/server";

export const mutation = mutationGeneric;
export const internalMutation = internalMutationGeneric;
export const query = queryGeneric;
export const internalQuery = internalQueryGeneric;
export const action = actionGeneric;
export const internalAction = internalActionGeneric;
export const httpAction = httpActionGeneric;
